site_name: Vesperia Guide
site_description: Missables checklist guide for Tales of Vesperia in Markdown format.
site_author: Huey Yeng
site_url: https://hueyyeng.github.io/VesperiaGuide/
repo_url: https://github.com/hueyyeng/VesperiaGuide

nav:
  - Home: index.md
  - Missables Checklist: missables.md
  - Spoiler-free Missables Checklist: missables_spoiler_free.md
  - Recipes Checklist: recipes.md
  - Labyrinth of Memories Map: labyrinth_memories_map/index.md
  - CHANGELOG: CHANGELOG.md

plugins:
  - search:
      lang: en
  - glightbox

markdown_extensions:
  - markdown_checklists.extension
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - js/checkbox.js

theme:
  name: material
  features:
    - search.suggest
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
       icon: material/weather-night
       name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
       icon: material/weather-sunny
       name: Switch to light mode

  logo: 'images/vesperia_logo.png'
